# Generated by Django 4.1.2 on 2023-02-21 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='دسته بندی')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='conclusion_date',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='تاریخ انعقاد'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contracting_party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contracting_party', to=settings.AUTH_USER_MODEL, verbose_name='طرف قرارداد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='end_date',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AddField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='فایل های ضمیمه شده'),
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(blank=True, choices=[('تکمیل شده', 'تکمیل شده'), ('تدوین قرارداد', 'تدوین قرارداد'), ('منتظر تایید', 'منتظر تایید'), ('منتظر امضا', 'منتظر امضا'), ('پایان مهلت امضا', 'پایان مهلت امضا')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='contract.category'),
        ),
    ]
