# Generated by Django 4.1.2 on 2023-05-28 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0001_initial'),
        ('contract', '0002_questionnaire_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='tag.tag'),
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('dedicated_approvers', models.ManyToManyField(related_name='dedicated_approvers_GeneralSettings', to=settings.AUTH_USER_MODEL)),
                ('public_approvers', models.ManyToManyField(related_name='public_approvers_GeneralSettings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('dedicated_approvers', models.ManyToManyField(related_name='dedicated_approvers_CustomSettings', to=settings.AUTH_USER_MODEL)),
                ('public_approvers', models.ManyToManyField(related_name='public_approvers_CustomSettings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
