# Generated by Django 4.1.2 on 2023-05-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_company_user_is_company_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='father_name',
        ),
    ]
