# Generated by Django 4.1.2 on 2023-05-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_remove_user_invitation_referral_invitationlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitationlink',
            old_name='active',
            new_name='unused',
        ),
    ]
