# Generated by Django 4.1.2 on 2023-05-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_rename_active_invitationlink_unused'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationlink',
            name='phone',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
