# Generated by Django 4.1.2 on 2023-02-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signature',
            old_name='body',
            new_name='description',
        ),
    ]
