# Generated by Django 4.1.2 on 2023-03-07 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('price', models.CharField(max_length=256)),
                ('signature_number', models.IntegerField()),
                ('contract_number', models.IntegerField()),
                ('duration_day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=256)),
                ('end_date', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('فعال', 'فعال'), ('به اتمام رسیده', 'به اتمام رسیده'), ('لغو شده', 'لغو شده')], max_length=256, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_subscription', to='subscription.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
